COMMENT ON TABLE COMTCADMINISTCODE IS '행정코드';

COMMENT ON COLUMN COMTCADMINISTCODE.ADMINIST_ZONE_SE IS '행정구역구분';

COMMENT ON COLUMN COMTCADMINISTCODE.ADMINIST_ZONE_CODE IS '행정구역코드';

COMMENT ON COLUMN COMTCADMINISTCODE.USE_AT IS '사용여부';

COMMENT ON COLUMN COMTCADMINISTCODE.ADMINIST_ZONE_NM IS '행정구역명';

COMMENT ON COLUMN COMTCADMINISTCODE.UPPER_ADMINIST_ZONE_CODE IS '상위행정구역코드';

COMMENT ON COLUMN COMTCADMINISTCODE.CREAT_DE IS '생성일자';

COMMENT ON COLUMN COMTCADMINISTCODE.ABL_DE IS '폐지일자';

COMMENT ON COLUMN COMTCADMINISTCODE.FRST_REGIST_PNTTM IS '최초등록시점';

COMMENT ON COLUMN COMTCADMINISTCODE.FRST_REGISTER_ID IS '최초등록자ID';

COMMENT ON COLUMN COMTCADMINISTCODE.LAST_UPDT_PNTTM IS '최종수정시점';

COMMENT ON COLUMN COMTCADMINISTCODE.LAST_UPDUSR_ID IS '최종수정자ID';
