CREATE TABLE COMTECOPSEQ
(
	TABLE_NAME            VARCHAR(20) NULL,
	NEXT_ID               NUMERIC(30) NULL,
	 PRIMARY KEY (TABLE_NAME)
)
;

CREATE UNIQUE INDEX COMTECOPSEQ_PK ON COMTECOPSEQ
(
	TABLE_NAME
)
;



CREATE TABLE COMTNEMPLYRSCRTYESTBS
(
	SCRTY_DTRMN_TRGET_ID  VARCHAR(20) NOT NULL,
	MBER_TY_CODE          CHAR(5) NULL,
	AUTHOR_CODE           VARCHAR(30) NOT NULL,
	 PRIMARY KEY (SCRTY_DTRMN_TRGET_ID)
)
;

CREATE UNIQUE INDEX COMTNEMPLYRSCRTYESTBS_PK ON COMTNEMPLYRSCRTYESTBS
(
	SCRTY_DTRMN_TRGET_ID
)
;
CREATE INDEX COMTNEMPLYRSCRTYESTBS_i04 ON COMTNEMPLYRSCRTYESTBS
(
	AUTHOR_CODE
)
;



CREATE TABLE COMTCCMMNCLCODE
(
	CL_CODE               CHAR(3) NOT NULL,
	CL_CODE_NM            VARCHAR(60) NULL,
	CL_CODE_DC            VARCHAR(200) NULL,
	USE_AT                CHAR(1) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	 PRIMARY KEY (CL_CODE)
)
;

CREATE UNIQUE INDEX COMTCCMMNCLCODE_PK ON COMTCCMMNCLCODE
(
	CL_CODE
)
;



CREATE TABLE COMTCCMMNCODE
(
	CODE_ID               VARCHAR(6) NOT NULL,
	CODE_ID_NM            VARCHAR(60) NULL,
	CODE_ID_DC            VARCHAR(200) NULL,
	USE_AT                CHAR(1) NULL,
	CL_CODE               CHAR(3) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	 PRIMARY KEY (CODE_ID),
	FOREIGN KEY COMTCCMMNCODE_FK1 (CL_CODE) REFERENCES COMTCCMMNCLCODE(CL_CODE)
)
;

CREATE UNIQUE INDEX COMTCCMMNCODE_PK ON COMTCCMMNCODE
(
	CODE_ID
)
;
CREATE INDEX COMTCCMMNCODE_i01 ON COMTCCMMNCODE
(
	CL_CODE
)
;



CREATE TABLE COMTCCMMNDETAILCODE
(
	CODE_ID               VARCHAR(6) NOT NULL,
	CODE                  VARCHAR(15) NOT NULL,
	CODE_NM               VARCHAR(60) NULL,
	CODE_DC               VARCHAR(200) NULL,
	USE_AT                CHAR(1) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	 PRIMARY KEY (CODE_ID,CODE),
	FOREIGN KEY COMTCCMMNDETAILCODE_FK1 (CODE_ID) REFERENCES COMTCCMMNCODE(CODE_ID)
)
;

CREATE UNIQUE INDEX COMTCCMMNDETAILCODE_PK ON COMTCCMMNDETAILCODE
(
	CODE_ID,
	CODE
)
;
CREATE INDEX COMTCCMMNDETAILCODE_i01 ON COMTCCMMNDETAILCODE
(
	CODE_ID
)
;



CREATE TABLE COMTNAUTHORGROUPINFO
(
	GROUP_ID              CHAR(20) NULL,
	GROUP_NM              VARCHAR(60) NOT NULL,
	GROUP_CREAT_DE        CHAR(20) NOT NULL,
	GROUP_DC              VARCHAR(100) NULL,
	 PRIMARY KEY (GROUP_ID)
)
;

CREATE UNIQUE INDEX COMTNAUTHORGROUPINFO_PK ON COMTNAUTHORGROUPINFO
(
	GROUP_ID
)
;



CREATE TABLE COMTNGNRLMBER
(
	MBER_ID               VARCHAR(20) NULL,
	PASSWORD              VARCHAR(200) NOT NULL,
	PASSWORD_HINT         VARCHAR(100) NULL,
	PASSWORD_CNSR         VARCHAR(100) NULL,
	IHIDNUM               VARCHAR(200) NULL,
	MBER_NM               VARCHAR(50) NOT NULL,
	ZIP                   VARCHAR(6) NOT NULL,
	ADRES                 VARCHAR(100) NOT NULL,
	AREA_NO               VARCHAR(4) NOT NULL,
	MBER_STTUS            VARCHAR(15) NULL,
	DETAIL_ADRES          VARCHAR(100) NULL,
	END_TELNO             VARCHAR(4) NOT NULL,
	MBTLNUM               VARCHAR(20) NOT NULL,
	GROUP_ID              CHAR(20) NULL,
	MBER_FXNUM            VARCHAR(20) NULL,
	MBER_EMAIL_ADRES      VARCHAR(50) NULL,
	MIDDLE_TELNO          VARCHAR(4) NOT NULL,
	SBSCRB_DE             DATETIME NULL,
	SEXDSTN_CODE          CHAR(1) NULL,
	ESNTL_ID              CHAR(20) NOT NULL,
	 PRIMARY KEY (MBER_ID),
	FOREIGN KEY COMTNGNRLMBER_FK1 (GROUP_ID) REFERENCES COMTNAUTHORGROUPINFO(GROUP_ID)
		ON DELETE SET NULL
)
;

CREATE UNIQUE INDEX COMTNGNRLMBER_PK ON COMTNGNRLMBER
(
	MBER_ID
)
;
CREATE INDEX COMTNGNRLMBER_i01 ON COMTNGNRLMBER
(
	GROUP_ID
)
;



CREATE TABLE COMTNORGNZTINFO
(
	ORGNZT_ID             CHAR(20) NULL,
	ORGNZT_NM             VARCHAR(20) NOT NULL,
	ORGNZT_DC             VARCHAR(100) NULL,
	 PRIMARY KEY (ORGNZT_ID)
)
;

CREATE UNIQUE INDEX COMTNORGNZTINFO_PK ON COMTNORGNZTINFO
(
	ORGNZT_ID
)
;



CREATE TABLE COMTNEMPLYRINFO
(
	EMPLYR_ID             VARCHAR(20) NOT NULL,
	ORGNZT_ID             CHAR(20) NULL,
	USER_NM               VARCHAR(60) NOT NULL,
	PASSWORD              VARCHAR(200) NOT NULL,
	EMPL_NO               VARCHAR(20) NULL,
	IHIDNUM               VARCHAR(200) NULL,
	SEXDSTN_CODE          CHAR(1) NULL,
	BRTHDY                CHAR(20) NULL,
	FXNUM                 VARCHAR(20) NULL,
	HOUSE_ADRES           VARCHAR(100) NOT NULL,
	PASSWORD_HINT         VARCHAR(100) NOT NULL,
	PASSWORD_CNSR         VARCHAR(100) NOT NULL,
	HOUSE_END_TELNO       VARCHAR(4) NOT NULL,
	AREA_NO               VARCHAR(4) NOT NULL,
	DETAIL_ADRES          VARCHAR(100) NULL,
	ZIP                   VARCHAR(6) NOT NULL,
	OFFM_TELNO            VARCHAR(20) NULL,
	MBTLNUM               VARCHAR(20) NULL,
	EMAIL_ADRES           VARCHAR(50) NULL,
	OFCPS_NM              VARCHAR(60) NULL,
	HOUSE_MIDDLE_TELNO    VARCHAR(4) NOT NULL,
	GROUP_ID              CHAR(20) NULL,
	PSTINST_CODE          CHAR(8) NULL,
	EMPLYR_STTUS_CODE     CHAR(1) NOT NULL,
	ESNTL_ID              CHAR(20) NOT NULL,
	CRTFC_DN_VALUE        VARCHAR(100) NULL,
	SBSCRB_DE             DATETIME NULL,
	 PRIMARY KEY (EMPLYR_ID),
	FOREIGN KEY COMTNEMPLYRINFO_FK2 (ORGNZT_ID) REFERENCES COMTNORGNZTINFO(ORGNZT_ID)
		ON DELETE SET NULL,
	FOREIGN KEY COMTNEMPLYRINFO_FK1 (GROUP_ID) REFERENCES COMTNAUTHORGROUPINFO(GROUP_ID)
		ON DELETE SET NULL
)
;

CREATE UNIQUE INDEX COMTNEMPLYRINFO_PK ON COMTNEMPLYRINFO
(
	EMPLYR_ID
)
;
CREATE INDEX COMTNEMPLYRINFO_i01 ON COMTNEMPLYRINFO
(
	ORGNZT_ID
)
;
CREATE INDEX COMTNEMPLYRINFO_i02 ON COMTNEMPLYRINFO
(
	GROUP_ID
)
;



CREATE TABLE COMTNENTRPRSMBER
(
	ENTRPRS_MBER_ID       VARCHAR(20) NULL,
	ENTRPRS_SE_CODE       CHAR(8) NULL,
	BIZRNO                VARCHAR(10) NULL,
	JURIRNO               VARCHAR(13) NULL,
	CMPNY_NM              VARCHAR(60) NOT NULL,
	CXFC                  VARCHAR(50) NULL,
	ZIP                   VARCHAR(6) NOT NULL,
	ADRES                 VARCHAR(100) NOT NULL,
	ENTRPRS_MIDDLE_TELNO  VARCHAR(4) NOT NULL,
	FXNUM                 VARCHAR(20) NULL,
	INDUTY_CODE           CHAR(1) NULL,
	APPLCNT_NM            VARCHAR(50) NOT NULL,
	APPLCNT_IHIDNUM       VARCHAR(200) NULL,
	SBSCRB_DE             DATETIME NULL,
	ENTRPRS_MBER_STTUS    VARCHAR(15) NULL,
	ENTRPRS_MBER_PASSWORD  VARCHAR(200) NULL,
	ENTRPRS_MBER_PASSWORD_HINT  VARCHAR(100) NOT NULL,
	ENTRPRS_MBER_PASSWORD_CNSR  VARCHAR(100) NOT NULL,
	GROUP_ID              CHAR(20) NULL,
	DETAIL_ADRES          VARCHAR(100) NULL,
	ENTRPRS_END_TELNO     VARCHAR(4) NOT NULL,
	AREA_NO               VARCHAR(4) NOT NULL,
	APPLCNT_EMAIL_ADRES   VARCHAR(50) NOT NULL,
	ESNTL_ID              CHAR(20) NOT NULL,
	 PRIMARY KEY (ENTRPRS_MBER_ID),
	FOREIGN KEY COMTNENTRPRSMBER_FK1 (GROUP_ID) REFERENCES COMTNAUTHORGROUPINFO(GROUP_ID)
		ON DELETE SET NULL
)
;

CREATE UNIQUE INDEX COMTNENTRPRSMBER_PK ON COMTNENTRPRSMBER
(
	ENTRPRS_MBER_ID
)
;
CREATE INDEX COMTNENTRPRSMBER_i01 ON COMTNENTRPRSMBER
(
	GROUP_ID
)
;





CREATE  VIEW COMVNUSERMASTER ( ESNTL_ID,USER_ID,PASSWORD,USER_NM,USER_ZIP,USER_ADRES,USER_EMAIL,GROUP_ID, USER_SE, ORGNZT_ID ) 
AS  
		SELECT ESNTL_ID, MBER_ID,PASSWORD,MBER_NM,ZIP,ADRES,MBER_EMAIL_ADRES,' ','GNR' AS USER_SE, ' ' ORGNZT_ID
		FROM COMTNGNRLMBER
		
	UNION ALL
		SELECT ESNTL_ID,EMPLYR_ID,PASSWORD,USER_NM,ZIP,HOUSE_ADRES,EMAIL_ADRES,GROUP_ID ,'USR' AS USER_SE, ORGNZT_ID
		FROM COMTNEMPLYRINFO
	UNION ALL
		SELECT ESNTL_ID,ENTRPRS_MBER_ID,ENTRPRS_MBER_PASSWORD,CMPNY_NM,ZIP,ADRES,APPLCNT_EMAIL_ADRES,' ' ,'ENT' AS USER_SE, ' ' ORGNZT_ID
		FROM COMTNENTRPRSMBER 
ORDER BY ESNTL_ID;


CREATE TABLE COMTNAUTHORINFO
(
	AUTHOR_CODE           VARCHAR(30) NULL,
	AUTHOR_NM             VARCHAR(60) NOT NULL,
	AUTHOR_DC             VARCHAR(200) NULL,
	AUTHOR_CREAT_DE       CHAR(20) NOT NULL,
	 PRIMARY KEY (AUTHOR_CODE)
)
;

CREATE UNIQUE INDEX COMTNAUTHORINFO_PK ON COMTNAUTHORINFO
(
	AUTHOR_CODE
)
;



CREATE TABLE COMTNROLES_HIERARCHY
(
	PARNTS_ROLE           VARCHAR(30) NOT NULL,
	CHLDRN_ROLE           VARCHAR(30) NOT NULL,
	 PRIMARY KEY (PARNTS_ROLE,CHLDRN_ROLE),
	FOREIGN KEY COMTNROLES_HIERARCHY_FK1 (PARNTS_ROLE) REFERENCES COMTNAUTHORINFO(AUTHOR_CODE)
		ON DELETE CASCADE,
	FOREIGN KEY COMTNROLES_HIERARCHY_FK2 (CHLDRN_ROLE) REFERENCES COMTNAUTHORINFO(AUTHOR_CODE)
		ON DELETE CASCADE
)
;

CREATE UNIQUE INDEX COMTNROLES_HIERARCHY_PK ON COMTNROLES_HIERARCHY
(
	PARNTS_ROLE,
	CHLDRN_ROLE
)
;
CREATE UNIQUE INDEX COMTNROLES_HIERARCHY_i01 ON COMTNROLES_HIERARCHY
(
	PARNTS_ROLE
)
;
CREATE INDEX COMTNROLES_HIERARCHY_i02 ON COMTNROLES_HIERARCHY
(
	CHLDRN_ROLE
)
;



CREATE TABLE COMTNROLEINFO
(
	ROLE_CODE             VARCHAR(50) NULL,
	ROLE_NM               VARCHAR(60) NOT NULL,
	ROLE_PTTRN            VARCHAR(300) NULL,
	ROLE_DC               VARCHAR(200) NULL,
	ROLE_TY               VARCHAR(80) NULL,
	ROLE_SORT             VARCHAR(10) NULL,
	ROLE_CREAT_DE         CHAR(20) NOT NULL,
	 PRIMARY KEY (ROLE_CODE)
)
;

CREATE UNIQUE INDEX COMTNROLEINFO_PK ON COMTNROLEINFO
(
	ROLE_CODE
)
;



CREATE TABLE COMTNAUTHORROLERELATE
(
	AUTHOR_CODE           VARCHAR(30) NOT NULL,
	ROLE_CODE             VARCHAR(50) NOT NULL,
	CREAT_DT              DATETIME NULL,
	 PRIMARY KEY (AUTHOR_CODE,ROLE_CODE),
	FOREIGN KEY COMTNAUTHORROLERELATE_FK1 (AUTHOR_CODE) REFERENCES COMTNAUTHORINFO(AUTHOR_CODE)
		ON DELETE CASCADE,
	FOREIGN KEY COMTNAUTHORROLERELATE_FK2 (ROLE_CODE) REFERENCES COMTNROLEINFO(ROLE_CODE)
		ON DELETE CASCADE
)
;

CREATE UNIQUE INDEX COMTNAUTHORROLERELATE_PK ON COMTNAUTHORROLERELATE
(
	AUTHOR_CODE,
	ROLE_CODE
)
;
CREATE INDEX COMTNAUTHORROLERELATE_i01 ON COMTNAUTHORROLERELATE
(
	AUTHOR_CODE
)
;
CREATE INDEX COMTNAUTHORROLERELATE_i02 ON COMTNAUTHORROLERELATE
(
	ROLE_CODE
)
;



CREATE TABLE COMTNFILE
(
	ATCH_FILE_ID          CHAR(20) NOT NULL,
	CREAT_DT              DATETIME NOT NULL,
	USE_AT                CHAR(1) NULL,
	 PRIMARY KEY (ATCH_FILE_ID)
)
;

CREATE UNIQUE INDEX COMTNFILE_PK ON COMTNFILE
(
	ATCH_FILE_ID
)
;



CREATE TABLE COMTNFILEDETAIL
(
	ATCH_FILE_ID          CHAR(20) NOT NULL,
	FILE_SN               NUMERIC(10) NOT NULL,
	FILE_STRE_COURS       VARCHAR(2000) NOT NULL,
	STRE_FILE_NM          VARCHAR(255) NOT NULL,
	ORIGNL_FILE_NM        VARCHAR(255) NULL,
	FILE_EXTSN            VARCHAR(20) NOT NULL,
	FILE_CN               MEDIUMTEXT NULL,
	FILE_SIZE             NUMERIC(8) NULL,
	 PRIMARY KEY (ATCH_FILE_ID,FILE_SN),
	FOREIGN KEY COMTNFILEDETAIL_FK1 (ATCH_FILE_ID) REFERENCES COMTNFILE(ATCH_FILE_ID)
)
;

CREATE UNIQUE INDEX COMTNFILEDETAIL_PK ON COMTNFILEDETAIL
(
	ATCH_FILE_ID,
	FILE_SN
)
;
CREATE INDEX COMTNFILEDETAIL_i01 ON COMTNFILEDETAIL
(
	ATCH_FILE_ID
)
;



CREATE TABLE COMTHEMAILDSPTCHMANAGE
(
	MSSAGE_ID             VARCHAR(20) NULL,
	EMAIL_CN              MEDIUMTEXT NULL,
	SNDR                  VARCHAR(50) NOT NULL,
	RCVER                 VARCHAR(50) NOT NULL,
	SJ                    VARCHAR(60) NOT NULL,
	SNDNG_RESULT_CODE     CHAR(1) NULL,
	DSPTCH_DT             CHAR(20) NOT NULL,
	ATCH_FILE_ID          CHAR(20) NULL,
	 PRIMARY KEY (MSSAGE_ID),
	FOREIGN KEY COMTHEMAILDSPTCHMANAGE_FK1 (SNDR) REFERENCES COMTNEMPLYRINFO(EMPLYR_ID),
	FOREIGN KEY COMTHEMAILDSPTCHMANAGE_FK2 (ATCH_FILE_ID) REFERENCES COMTNFILE(ATCH_FILE_ID)
)
;

CREATE UNIQUE INDEX COMTHEMAILDSPTCHMANAGE_PK ON COMTHEMAILDSPTCHMANAGE
(
	MSSAGE_ID
)
;
CREATE INDEX COMTHEMAILDSPTCHMANAGE_i01 ON COMTHEMAILDSPTCHMANAGE
(
	SNDR
)
;
CREATE INDEX COMTHEMAILDSPTCHMANAGE_i02 ON COMTHEMAILDSPTCHMANAGE
(
	ATCH_FILE_ID
)
;



CREATE TABLE COMTNNCRD
(
	NCRD_ID               CHAR(20) NOT NULL,
	NCRD_TRGTER_ID        VARCHAR(20) NULL,
	NM                    VARCHAR(50) NOT NULL,
	TELNO                 VARCHAR(20) NULL,
	NATION_NO             VARCHAR(10) NULL,
	AREA_NO               VARCHAR(4) NULL,
	MIDDLE_TELNO          VARCHAR(4) NULL,
	END_TELNO             VARCHAR(4) NULL,
	MBTLNUM               VARCHAR(20) NULL,
	IDNTFC_NO             VARCHAR(10) NULL,
	MIDDLE_MBTLNUM        VARCHAR(4) NULL,
	END_MBTLNUM           VARCHAR(4) NULL,
	EMAIL_ADRES           VARCHAR(50) NULL,
	CMPNY_NM              VARCHAR(60) NULL,
	DEPT_NM               VARCHAR(60) NULL,
	ADRES                 VARCHAR(100) NULL,
	DETAIL_ADRES          VARCHAR(100) NULL,
	OFCPS_NM              VARCHAR(60) NULL,
	CLSF_NM               VARCHAR(60) NULL,
	EXTRL_USER_AT         CHAR(1) NULL,
	OTHBC_AT              CHAR(1) NOT NULL,
	RM                    VARCHAR(2500) NULL,
	FRST_REGIST_PNTTM     DATETIME NOT NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	 PRIMARY KEY (NCRD_ID)
)
;

CREATE UNIQUE INDEX COMTNNCRD_PK ON COMTNNCRD
(
	NCRD_ID
)
;



CREATE TABLE COMTNADBKMANAGE
(
	ADBK_ID               CHAR(20) NOT NULL,
	ADBK_NM               VARCHAR(50) NOT NULL,
	OTHBC_SCOPE           VARCHAR(20) NOT NULL,
	USE_AT                CHAR(1) NOT NULL,
	WRTER_ID              VARCHAR(20) NULL,
	TRGET_ORGNZT_ID       CHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NOT NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NOT NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	 PRIMARY KEY (ADBK_ID)
)
;

CREATE UNIQUE INDEX COMTNADBKMANAGE_PK ON COMTNADBKMANAGE
(
	ADBK_ID
)
;



CREATE TABLE COMTNADBK
(
	EMPLYR_ID             VARCHAR(20) NULL,
	NCRD_ID               CHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	ADBK_CONSTNT_ID       CHAR(20) NOT NULL,
	NM                    VARCHAR(50) NULL,
	EMAIL_ADRES           VARCHAR(50) NULL,
	MBTLNUM               VARCHAR(20) NULL,
	FXNUM                 VARCHAR(20) NULL,
	OFFM_TELNO            VARCHAR(20) NULL,
	HOUSE_TELNO           VARCHAR(20) NULL,
	ADBK_ID               CHAR(20) NOT NULL,
	 PRIMARY KEY (ADBK_CONSTNT_ID,ADBK_ID),
	FOREIGN KEY COMTNADBK_FK1 (ADBK_ID) REFERENCES COMTNADBKMANAGE(ADBK_ID)
		ON DELETE CASCADE
)
;

CREATE UNIQUE INDEX COMTNADBK_PK ON COMTNADBK
(
	ADBK_CONSTNT_ID,
	ADBK_ID
)
;
CREATE INDEX COMTNADBK_i01 ON COMTNADBK
(
	ADBK_ID
)
;



CREATE TABLE COMTNTMPLATINFO
(
	TMPLAT_ID             CHAR(20) NULL,
	TMPLAT_NM             VARCHAR(255) NULL,
	TMPLAT_COURS          VARCHAR(2000) NULL,
	USE_AT                CHAR(1) NULL,
	TMPLAT_SE_CODE        CHAR(6) NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	 PRIMARY KEY (TMPLAT_ID)
)
;

CREATE UNIQUE INDEX COMTNTMPLATINFO_PK ON COMTNTMPLATINFO
(
	TMPLAT_ID
)
;



CREATE TABLE COMTNRESTDE
(
	RESTDE_NO             NUMERIC(6) NOT NULL,
	RESTDE                CHAR(8) NULL,
	RESTDE_NM             VARCHAR(60) NULL,
	RESTDE_DC             VARCHAR(200) NULL,
	RESTDE_SE_CODE        VARCHAR(2) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	 PRIMARY KEY (RESTDE_NO)
)
;

CREATE UNIQUE INDEX COMTNRESTDE_PK ON COMTNRESTDE
(
	RESTDE_NO
)
;



CREATE TABLE COMTNBBSMASTER
(
	BBS_ID                CHAR(20) NOT NULL,
	BBS_NM                VARCHAR(255) NOT NULL,
	BBS_INTRCN            VARCHAR(2400) NULL,
	BBS_TY_CODE           CHAR(6) NOT NULL,
	BBS_ATTRB_CODE        CHAR(6) NOT NULL,
	REPLY_POSBL_AT        CHAR(1) NULL,
	FILE_ATCH_POSBL_AT    CHAR(1) NOT NULL,
	ATCH_POSBL_FILE_NUMBER  NUMERIC(2) NOT NULL,
	ATCH_POSBL_FILE_SIZE  NUMERIC(8) NULL,
	USE_AT                CHAR(1) NOT NULL,
	TMPLAT_ID             CHAR(20) NULL,
	FRST_REGISTER_ID      VARCHAR(20) NOT NULL,
	FRST_REGIST_PNTTM     DATETIME NOT NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	 PRIMARY KEY (BBS_ID)
)
;

CREATE UNIQUE INDEX COMTNBBSMASTER_PK ON COMTNBBSMASTER
(
	BBS_ID
)
;



CREATE TABLE COMTNBBSUSE
(
	BBS_ID                CHAR(20) NOT NULL,
	TRGET_ID              CHAR(20) NULL,
	USE_AT                CHAR(1) NOT NULL,
	REGIST_SE_CODE        CHAR(6) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NOT NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	 PRIMARY KEY (BBS_ID,TRGET_ID),
	FOREIGN KEY COMTNBBSUSE_FK1 (BBS_ID) REFERENCES COMTNBBSMASTER(BBS_ID)
)
;

CREATE UNIQUE INDEX COMTNBBSUSE_PK ON COMTNBBSUSE
(
	BBS_ID,
	TRGET_ID
)
;
CREATE INDEX COMTNBBSUSE_i01 ON COMTNBBSUSE
(
	BBS_ID
)
;



CREATE TABLE COMTNBBS
(
	NTT_ID                NUMERIC(20) NOT NULL,
	BBS_ID                CHAR(20) NOT NULL,
	NTT_NO                NUMERIC(20) NULL,
	NTT_SJ                VARCHAR(2000) NULL,
	NTT_CN                MEDIUMTEXT NULL,
	ANSWER_AT             CHAR(1) NULL,
	PARNTSCTT_NO          NUMERIC(10) NULL,
	ANSWER_LC             NUMERIC(8) NULL,
	SORT_ORDR             NUMERIC(8) NULL,
	RDCNT                 NUMERIC(10) NULL,
	USE_AT                CHAR(1) NOT NULL,
	NTCE_BGNDE            CHAR(20) NULL,
	NTCE_ENDDE            CHAR(20) NULL,
	NTCR_ID               VARCHAR(20) NULL,
	NTCR_NM               VARCHAR(20) NULL,
	PASSWORD              VARCHAR(200) NULL,
	ATCH_FILE_ID          CHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NOT NULL,
	FRST_REGISTER_ID      VARCHAR(20) NOT NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	 PRIMARY KEY (NTT_ID,BBS_ID),
	FOREIGN KEY COMTNBBS_FK1 (BBS_ID) REFERENCES COMTNBBSMASTER(BBS_ID)
)
;

CREATE UNIQUE INDEX COMTNBBS_PK ON COMTNBBS
(
	NTT_ID,
	BBS_ID
)
;
CREATE INDEX COMTNBBS_i01 ON COMTNBBS
(
	BBS_ID
)
;



CREATE TABLE COMTNCMMNTY
(
	CMMNTY_ID             CHAR(20) NOT NULL,
	CMMNTY_NM             VARCHAR(255) NOT NULL,
	CMMNTY_INTRCN         VARCHAR(2400) NULL,
	USE_AT                CHAR(1) NOT NULL,
	REGIST_SE_CODE        CHAR(6) NULL,
	TMPLAT_ID             CHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NOT NULL,
	FRST_REGISTER_ID      VARCHAR(20) NOT NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	 PRIMARY KEY (CMMNTY_ID)
)
;

CREATE UNIQUE INDEX COMTNCMMNTY_PK ON COMTNCMMNTY
(
	CMMNTY_ID
)
;



CREATE TABLE COMTNCLUB
(
	CLB_ID                CHAR(20) NOT NULL,
	CMMNTY_ID             CHAR(20) NOT NULL,
	CLB_NM                VARCHAR(255) NOT NULL,
	CLB_INTRCN            VARCHAR(2400) NULL,
	USE_AT                CHAR(1) NOT NULL,
	REGIST_SE_CODE        CHAR(6) NULL,
	TMPLAT_ID             CHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NOT NULL,
	FRST_REGISTER_ID      VARCHAR(20) NOT NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	 PRIMARY KEY (CLB_ID,CMMNTY_ID)
)
;

CREATE UNIQUE INDEX COMTNCLUB_PK ON COMTNCLUB
(
	CLB_ID,
	CMMNTY_ID
)
;



CREATE TABLE COMTNBBSMASTEROPTN
(
	BBS_ID                CHAR(20) NOT NULL,
	ANSWER_AT             CHAR(1) NOT NULL,
	STSFDG_AT             CHAR(1) NOT NULL,
	FRST_REGIST_PNTTM     DATETIME NOT NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NOT NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	 PRIMARY KEY (BBS_ID)
)
;

CREATE UNIQUE INDEX COMTNBBSMASTEROPTN_PK ON COMTNBBSMASTEROPTN
(
	BBS_ID
)
;



CREATE TABLE COMTNCOMMENT
(
	NTT_ID                NUMERIC(20) NOT NULL,
	BBS_ID                CHAR(20) NOT NULL,
	ANSWER_NO             NUMERIC(20) NOT NULL,
	WRTER_ID              VARCHAR(20) NULL,
	WRTER_NM              VARCHAR(20) NULL,
	ANSWER                VARCHAR(200) NULL,
	USE_AT                CHAR(1) NOT NULL,
	FRST_REGIST_PNTTM     DATETIME NOT NULL,
	FRST_REGISTER_ID      VARCHAR(20) NOT NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	PASSWORD              VARCHAR(200) NULL,
	 PRIMARY KEY (NTT_ID,BBS_ID,ANSWER_NO),
	FOREIGN KEY COMTNCOMMENT_FK1 (NTT_ID,BBS_ID) REFERENCES COMTNBBS(NTT_ID,BBS_ID)
)
;

CREATE UNIQUE INDEX COMTNCOMMENT_PK ON COMTNCOMMENT
(
	NTT_ID,
	BBS_ID,
	ANSWER_NO
)
;
CREATE INDEX COMTNCOMMENT_i01 ON COMTNCOMMENT
(
	NTT_ID,
	BBS_ID
)
;



CREATE TABLE COMTHCONFMHISTORY
(
	CONFM_NO              NUMERIC(8) NOT NULL,
	CONFM_RQESTER_ID      VARCHAR(20) NOT NULL,
	CONFMER_ID            VARCHAR(20) NULL,
	CONFM_DE              CHAR(20) NULL,
	CONFM_TY_CODE         CHAR(4) NOT NULL,
	CONFM_STTUS_CODE      CHAR(4) NOT NULL,
	OPERT_TY_CODE         CHAR(4) NULL,
	OPERT_ID              VARCHAR(20) NULL,
	TRGET_JOB_TY_CODE     CHAR(3) NULL,
	TRGET_JOB_ID          CHAR(20) NULL,
	 PRIMARY KEY (CONFM_NO)
)
;

CREATE UNIQUE INDEX COMTHCONFMHISTORY_PK ON COMTHCONFMHISTORY
(
	CONFM_NO
)
;



CREATE TABLE COMTNCMMNTYUSER
(
	CMMNTY_ID             CHAR(20) NOT NULL,
	EMPLYR_ID             VARCHAR(20) NOT NULL,
	MNGR_AT               CHAR(1) NOT NULL,
	SBSCRB_DE             DATETIME NULL,
	SECSN_DE              CHAR(20) NULL,
	USE_AT                CHAR(1) NULL,
	FRST_REGIST_PNTTM     DATETIME NOT NULL,
	FRST_REGISTER_ID      VARCHAR(20) NOT NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	 PRIMARY KEY (CMMNTY_ID,EMPLYR_ID),
	FOREIGN KEY COMTNCMMNTYUSER_FK1 (CMMNTY_ID) REFERENCES COMTNCMMNTY(CMMNTY_ID)
)
;

CREATE UNIQUE INDEX COMTNCMMNTYUSER_PK ON COMTNCMMNTYUSER
(
	CMMNTY_ID,
	EMPLYR_ID
)
;
CREATE INDEX COMTNCMMNTYUSER_i01 ON COMTNCMMNTYUSER
(
	CMMNTY_ID
)
;



CREATE TABLE COMTNCLUBUSER
(
	CLB_ID                CHAR(20) NOT NULL,
	CMMNTY_ID             CHAR(20) NOT NULL,
	OPRTR_AT              CHAR(1) NOT NULL,
	SBSCRB_DE             DATETIME NULL,
	SECSN_DE              CHAR(20) NULL,
	USE_AT                CHAR(1) NOT NULL,
	FRST_REGIST_PNTTM     DATETIME NOT NULL,
	FRST_REGISTER_ID      VARCHAR(20) NOT NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	EMPLYR_ID             VARCHAR(20) NOT NULL,
	 PRIMARY KEY (CLB_ID,CMMNTY_ID,EMPLYR_ID),
	FOREIGN KEY COMTNCLUBUSER_FK1 (CLB_ID,CMMNTY_ID) REFERENCES COMTNCLUB(CLB_ID,CMMNTY_ID)
)
;

CREATE UNIQUE INDEX COMTNCLUBUSER_PK ON COMTNCLUBUSER
(
	CLB_ID,
	CMMNTY_ID,
	EMPLYR_ID
)
;
CREATE INDEX COMTNCLUBUSER_i01 ON COMTNCLUBUSER
(
	CLB_ID,
	CMMNTY_ID
)
;



CREATE TABLE COMTNSCRAP
(
	SCRAP_ID              CHAR(20) NOT NULL,
	NTT_ID                NUMERIC(20) NOT NULL,
	BBS_ID                CHAR(20) NOT NULL,
	SCRAP_NM              VARCHAR(100) NOT NULL,
	USE_AT                CHAR(1) NOT NULL,
	FRST_REGIST_PNTTM     DATETIME NOT NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NOT NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	 PRIMARY KEY (SCRAP_ID)
)
;

CREATE UNIQUE INDEX COMTNSCRAP_PK ON COMTNSCRAP
(
	SCRAP_ID
)
;



CREATE TABLE COMTNMTGINFO
(
	MTG_ID                CHAR(20) NOT NULL,
	MTG_NM                VARCHAR(255) NULL,
	MTG_MTR_CN            VARCHAR(1000) NULL,
	MTG_SN                NUMERIC(10) NULL,
	MTG_CO                NUMERIC(5) NULL,
	MTG_DE                CHAR(20) NULL,
	MTG_PLACE             VARCHAR(255) NULL,
	MTG_BEGIN_TM          VARCHAR(14) NULL,
	MTG_END_TM            VARCHAR(14) NULL,
	CLSDR_MTG_AT          CHAR(1) NULL,
	READNG_BGNDE          CHAR(20) NULL,
	READNG_AT             CHAR(1) NULL,
	MTG_RESULT_CN         VARCHAR(1000) NULL,
	MTG_RESULT_ENNC       CHAR(1) NULL,
	ETC_MATTER            VARCHAR(1000) NULL,
	MNGT_DEPT_ID          VARCHAR(20) NULL,
	MNAER_ID              VARCHAR(20) NULL,
	MNAER_DEPT_ID         VARCHAR(20) NULL,
	MTG_AT                CHAR(1) NULL,
	NONATDRN_CO           NUMERIC(10) NULL,
	ATDRN_CO              NUMERIC(10) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	 PRIMARY KEY (MTG_ID)
)
;

CREATE UNIQUE INDEX COMTNMTGINFO_PK ON COMTNMTGINFO
(
	MTG_ID
)
;



CREATE TABLE COMTNSCHDULINFO
(
	SCHDUL_ID             CHAR(20) NOT NULL,
	SCHDUL_SE             CHAR(1) NULL,
	SCHDUL_DEPT_ID        VARCHAR(20) NULL,
	SCHDUL_KND_CODE       CHAR(1) NULL,
	SCHDUL_BGNDE          CHAR(20) NULL,
	SCHDUL_ENDDE          CHAR(20) NULL,
	SCHDUL_NM             VARCHAR(255) NULL,
	SCHDUL_CN             VARCHAR(2500) NULL,
	SCHDUL_PLACE          VARCHAR(255) NULL,
	SCHDUL_IPCR_CODE      CHAR(1) NULL,
	SCHDUL_CHARGER_ID     VARCHAR(20) NULL,
	ATCH_FILE_ID          CHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	REPTIT_SE_CODE        CHAR(1) NULL,
	 PRIMARY KEY (SCHDUL_ID)
)
;

CREATE UNIQUE INDEX COMTNSCHDULINFO_PK ON COMTNSCHDULINFO
(
	SCHDUL_ID
)
;



CREATE TABLE COMTNDIARYINFO
(
	SCHDUL_ID             CHAR(20) NOT NULL,
	DIARY_ID              CHAR(20) NOT NULL,
	DIARY_PROGRSRT        NUMERIC(3) NULL,
	DIARY_NM              VARCHAR(255) NULL,
	DRCT_MATTER           VARCHAR(2500) NULL,
	PARTCLR_MATTER        VARCHAR(2500) NULL,
	ATCH_FILE_ID          CHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	 PRIMARY KEY (SCHDUL_ID,DIARY_ID),
	FOREIGN KEY COMTNDIARYINFO_FK1 (SCHDUL_ID) REFERENCES COMTNSCHDULINFO(SCHDUL_ID)
)
;

CREATE UNIQUE INDEX COMTNDIARYINFO_PK ON COMTNDIARYINFO
(
	SCHDUL_ID,
	DIARY_ID
)
;
CREATE INDEX COMTNDIARYINFO_i01 ON COMTNDIARYINFO
(
	SCHDUL_ID
)
;



CREATE TABLE COMTNGEOLOCATION
(
	SN                    INT(20) NOT NULL,
	MBER_ID               VARCHAR(20) NOT NULL,
	BULD_NM               VARCHAR(60) NOT NULL,
	LA                    VARCHAR(48) NULL,
	LO                    VARCHAR(48) NULL,
	TELNO                 VARCHAR(20) NULL,
	ADRES                 VARCHAR(100) NULL,
	CONSTRAINT  COMTNGEOLOCATION_PK PRIMARY KEY (SN)
);



CREATE TABLE COMTNDEVICE
(
	SN                    INT(20) NOT NULL,
	MBER_ID               VARCHAR(20) NOT NULL,
	UAGENT_INFO           VARCHAR(1024) NULL,
	BROWSER_CODE_ID       VARCHAR(6) NULL,
	BROWSER_CODE          VARCHAR(15) NULL,
	OS_CODE_ID            VARCHAR(6) NULL,
	OS_CODE               VARCHAR(15) NULL,
	RECENT_CODE_ID        VARCHAR(6) NULL,
	RECENT_CODE           VARCHAR(15) NULL,
	CREAT_DT             DATE NOT NULL,
	UPDT_DT               DATE NOT NULL,
	CONSTRAINT  COMTNDEVICE_PK PRIMARY KEY (SN)
);



CREATE TABLE COMTNMOBILEMENUINFO

(
	MENU_CODE			VARCHAR(20) NOT NULL,
	MENU_NM      		VARCHAR(60) NULL,
	MENU_LVL			NUMERIC(5) NULL,
	CNNC_URL			VARCHAR(255) NULL,
	MENU_DC				VARCHAR(250) NULL,
	ACTVTY_AT			CHAR(1) NULL,
	UPPER_MENU_ID		VARCHAR(20) NULL,
	
	FRST_REGIST_PNTTM	DATETIME NULL,
	
	FRST_REGISTER_ID	VARCHAR(20) NULL,
	
	LAST_UPDT_PNTTM		DATETIME NULL,
	
	LAST_UPDUSR_ID		VARCHAR(20) NULL,
	 PRIMARY KEY (MENU_CODE)
)
;




CREATE TABLE COMTNREALTIMENOTICE
(
	SN                    INT(20) NOT NULL,
	MBER_ID               VARCHAR(20) NOT NULL,
	NOTICE_SJ             VARCHAR(256) NULL,
	NOTICE_CN             VARCHAR(2048) NULL,
	RECENT_CODE_ID        VARCHAR(6) NULL,
	RECENT_CODE           VARCHAR(15) NULL,
	NOTICE_BGNDT          DATE NOT NULL,
	NOTICE_ENDDT          DATE NOT NULL,
	CREAT_DT             DATE NOT NULL,
	UPDT_DT               DATE NOT NULL,
	CONSTRAINT  COMTNREALTIMENOTICE_PK PRIMARY KEY (SN)
);



CREATE TABLE COMTNSYNC
(
	SN                    INT(20) NOT NULL,
	MBER_ID               VARCHAR(20) NOT NULL,
	SYNC_SJ               VARCHAR(256) NULL,
	SYNC_CN               VARCHAR(2048) NULL,
	SYNC_DT               DATE NULL,
	CREAT_DT             DATE NOT NULL,
	UPDT_DT               DATE NOT NULL,
	CONSTRAINT  COMTNSYNC_PK PRIMARY KEY (SN)
);


CREATE TABLE COMTNOFFLINEWEB
(
	SN                    INT(20) NOT NULL,
	MBER_ID               VARCHAR(20) NOT NULL,
	OFFLINE_SJ            VARCHAR(256) NULL,
	OFFLINE_CN            VARCHAR(2048) NULL,
	CREAT_DT             DATE NOT NULL,
	UPDT_DT               DATE NOT NULL,
	CONSTRAINT  COMTNOFFLINEWEB_PK PRIMARY KEY (SN)
);