INSERT INTO COMTECOPSEQ ( TABLE_NAME, NEXT_ID ) VALUES ('MOBILE_MENU_ID',101);

DELETE FROM COMTNMOBILEMENUINFO;

INSERT INTO COMTNMOBILEMENUINFO ( MENU_CODE, MENU_NM, MENU_LVL, CNNC_URL, MENU_DC, ACTVTY_AT, UPPER_MENU_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID ) VALUES ('MENU_0000000001','사용자지원',1,'','카테고리',1,'',SYSDATE,'SYSTEM');
INSERT INTO COMTNMOBILEMENUINFO ( MENU_CODE, MENU_NM, MENU_LVL, CNNC_URL, MENU_DC, ACTVTY_AT, UPPER_MENU_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID ) VALUES ('MENU_0000000002','협업'      ,1,'','카테고리',1,'',SYSDATE,'SYSTEM');
INSERT INTO COMTNMOBILEMENUINFO ( MENU_CODE, MENU_NM, MENU_LVL, CNNC_URL, MENU_DC, ACTVTY_AT, UPPER_MENU_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID ) VALUES ('MENU_0000000003','기타'      ,1,'','카테고리',1,'',SYSDATE,'SYSTEM');

INSERT INTO COMTNMOBILEMENUINFO ( MENU_CODE, MENU_NM, MENU_LVL, CNNC_URL, MENU_DC, ACTVTY_AT, UPPER_MENU_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID ) VALUES ('MENU_0000000011','약관관리'                                  ,2,'/uss/sam/stp/StplatListInqire.mdo'                   ,'약관관리'                                  ,0,'MENU_0000000001',SYSDATE,'SYSTEM');
INSERT INTO COMTNMOBILEMENUINFO ( MENU_CODE, MENU_NM, MENU_LVL, CNNC_URL, MENU_DC, ACTVTY_AT, UPPER_MENU_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID ) VALUES ('MENU_0000000012','상담관리'                                  ,2,'/uss/olp/cns/CnsltListInqire.mdo'                    ,'상담관리'                                  ,0,'MENU_0000000001',SYSDATE,'SYSTEM');
INSERT INTO COMTNMOBILEMENUINFO ( MENU_CODE, MENU_NM, MENU_LVL, CNNC_URL, MENU_DC, ACTVTY_AT, UPPER_MENU_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID ) VALUES ('MENU_0000000013','설문참여'                                  ,2,'/uss/olp/qnn/EgovQustnrRespondInfoManageListView.mdo','설문참여'                                  ,0,'MENU_0000000001',SYSDATE,'SYSTEM');
INSERT INTO COMTNMOBILEMENUINFO ( MENU_CODE, MENU_NM, MENU_LVL, CNNC_URL, MENU_DC, ACTVTY_AT, UPPER_MENU_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID ) VALUES ('MENU_0000000014','온라인POLL참여'                            ,2,'/uss/olp/opp/listOnlinePollPartcptn.mdo'             ,'온라인POLL참여'                            ,0,'MENU_0000000001',SYSDATE,'SYSTEM');
INSERT INTO COMTNMOBILEMENUINFO ( MENU_CODE, MENU_NM, MENU_LVL, CNNC_URL, MENU_DC, ACTVTY_AT, UPPER_MENU_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID ) VALUES ('MENU_0000000015','도움말'                                    ,2,'/uss/olh/hpc/HpcmListInqire.mdo'                     ,'도움말'                                    ,0,'MENU_0000000001',SYSDATE,'SYSTEM');
INSERT INTO COMTNMOBILEMENUINFO ( MENU_CODE, MENU_NM, MENU_LVL, CNNC_URL, MENU_DC, ACTVTY_AT, UPPER_MENU_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID ) VALUES ('MENU_0000000016','용어사전'                                  ,2,'/uss/olh/wor/WordDicaryListInqire.mdo'               ,'용어사전'                                  ,0,'MENU_0000000001',SYSDATE,'SYSTEM');
INSERT INTO COMTNMOBILEMENUINFO ( MENU_CODE, MENU_NM, MENU_LVL, CNNC_URL, MENU_DC, ACTVTY_AT, UPPER_MENU_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID ) VALUES ('MENU_0000000017','FAQ'                                       ,2,'/uss/olh/faq/FaqListInqire.mdo'                      ,'FAQ'                                       ,0,'MENU_0000000001',SYSDATE,'SYSTEM');
INSERT INTO COMTNMOBILEMENUINFO ( MENU_CODE, MENU_NM, MENU_LVL, CNNC_URL, MENU_DC, ACTVTY_AT, UPPER_MENU_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID ) VALUES ('MENU_0000000018','Q&A'                                       ,2,'/uss/olh/qna/QnaListInqire.mdo'                      ,'Q&A'                                       ,0,'MENU_0000000001',SYSDATE,'SYSTEM');
INSERT INTO COMTNMOBILEMENUINFO ( MENU_CODE, MENU_NM, MENU_LVL, CNNC_URL, MENU_DC, ACTVTY_AT, UPPER_MENU_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID ) VALUES ('MENU_0000000019','행정전문용어사전'                          ,2,'/uss/olh/awa/listAdministrationWord.mdo'             ,'행정전문용어사전'                          ,0,'MENU_0000000001',SYSDATE,'SYSTEM');
INSERT INTO COMTNMOBILEMENUINFO ( MENU_CODE, MENU_NM, MENU_LVL, CNNC_URL, MENU_DC, ACTVTY_AT, UPPER_MENU_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID ) VALUES ('MENU_0000000010','온라인매뉴얼'                              ,2,'/uss/olh/omm/listOnlineManual.mdo'                   ,'온라인매뉴얼'                              ,0,'MENU_0000000001',SYSDATE,'SYSTEM');
INSERT INTO COMTNMOBILEMENUINFO ( MENU_CODE, MENU_NM, MENU_LVL, CNNC_URL, MENU_DC, ACTVTY_AT, UPPER_MENU_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID ) VALUES ('MENU_0000000020','뉴스 목록'                                 ,2,'/uss/ion/nws/NewsInfoListInqire.mdo'                 ,'뉴스 목록'                                 ,0,'MENU_0000000001',SYSDATE,'SYSTEM');
INSERT INTO COMTNMOBILEMENUINFO ( MENU_CODE, MENU_NM, MENU_LVL, CNNC_URL, MENU_DC, ACTVTY_AT, UPPER_MENU_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID ) VALUES ('MENU_0000000021','사이트맵 Type 1'                           ,2,'/sym/mnu/mcm/EgovWebSiteMapView.mdo'                 ,'사이트맵 Type 1'                           ,0,'MENU_0000000001',SYSDATE,'SYSTEM');
INSERT INTO COMTNMOBILEMENUINFO ( MENU_CODE, MENU_NM, MENU_LVL, CNNC_URL, MENU_DC, ACTVTY_AT, UPPER_MENU_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID ) VALUES ('MENU_0000000022','사이트맵 Type 2'                           ,2,'/sym/mnu/mcm/EgovSiteMapng.mdo'                      ,'사이트맵 Type 2'                           ,0,'MENU_0000000001',SYSDATE,'SYSTEM');
INSERT INTO COMTNMOBILEMENUINFO ( MENU_CODE, MENU_NM, MENU_LVL, CNNC_URL, MENU_DC, ACTVTY_AT, UPPER_MENU_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID ) VALUES ('MENU_0000000023','추천사이트'                                ,2,'/uss/ion/rec/RecomendSiteListInqire.mdo'             ,'추천사이트'                                ,0,'MENU_0000000001',SYSDATE,'SYSTEM');
INSERT INTO COMTNMOBILEMENUINFO ( MENU_CODE, MENU_NM, MENU_LVL, CNNC_URL, MENU_DC, ACTVTY_AT, UPPER_MENU_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID ) VALUES ('MENU_0000000024','행사/이벤트/캠페인'                        ,2,'/uss/ion/ecc/EgovEventCmpgnList.mdo'                 ,'행사/이벤트/캠페인'                        ,0,'MENU_0000000001',SYSDATE,'SYSTEM');
INSERT INTO COMTNMOBILEMENUINFO ( MENU_CODE, MENU_NM, MENU_LVL, CNNC_URL, MENU_DC, ACTVTY_AT, UPPER_MENU_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID ) VALUES ('MENU_0000000025','마이페이지'                                ,2,'/uss/mpe/selectIndvdlpgeResult.mdo'                  ,'마이페이지'                                ,0,'MENU_0000000001',SYSDATE,'SYSTEM');
                                                                                                                                                                                                                                                                                                                               
INSERT INTO COMTNMOBILEMENUINFO ( MENU_CODE, MENU_NM, MENU_LVL, CNNC_URL, MENU_DC, ACTVTY_AT, UPPER_MENU_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID ) VALUES ('MENU_0000000026','스크랩'                                    ,2,'/cop/scp/selectScrapList.mdo'                        ,'스크랩'                                    ,1,'MENU_0000000002',SYSDATE,'SYSTEM');
INSERT INTO COMTNMOBILEMENUINFO ( MENU_CODE, MENU_NM, MENU_LVL, CNNC_URL, MENU_DC, ACTVTY_AT, UPPER_MENU_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID ) VALUES ('MENU_0000000027','부서일정관리'                              ,2,'/cop/smt/sdm/EgovDeptSchdulManageDailyList.mdo'      ,'부서일정관리'                              ,1,'MENU_0000000002',SYSDATE,'SYSTEM');
INSERT INTO COMTNMOBILEMENUINFO ( MENU_CODE, MENU_NM, MENU_LVL, CNNC_URL, MENU_DC, ACTVTY_AT, UPPER_MENU_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID ) VALUES ('MENU_0000000028','일정관리'                                  ,2,'/cop/smt/sim/EgovIndvdlSchdulManageDailyList.mdo'    ,'일정관리'                                  ,1,'MENU_0000000002',SYSDATE,'SYSTEM');
INSERT INTO COMTNMOBILEMENUINFO ( MENU_CODE, MENU_NM, MENU_LVL, CNNC_URL, MENU_DC, ACTVTY_AT, UPPER_MENU_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID ) VALUES ('MENU_0000000029','일지관리'                                  ,2,'/cop/smt/dsm/EgovDiaryManageList.mdo'                ,'일지관리'                                  ,1,'MENU_0000000002',SYSDATE,'SYSTEM');
INSERT INTO COMTNMOBILEMENUINFO ( MENU_CODE, MENU_NM, MENU_LVL, CNNC_URL, MENU_DC, ACTVTY_AT, UPPER_MENU_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID ) VALUES ('MENU_0000000030','전체일정 목록'                             ,2,'/cop/smt/sam/EgovAllSchdulManageList.mdo'            ,'전체일정 목록'                             ,1,'MENU_0000000002',SYSDATE,'SYSTEM');
INSERT INTO COMTNMOBILEMENUINFO ( MENU_CODE, MENU_NM, MENU_LVL, CNNC_URL, MENU_DC, ACTVTY_AT, UPPER_MENU_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID ) VALUES ('MENU_0000000031','주소록관리'                                ,2,'/cop/adb/selectAdbkList.mdo'                         ,'주소록관리'                                ,1,'MENU_0000000002',SYSDATE,'SYSTEM');
INSERT INTO COMTNMOBILEMENUINFO ( MENU_CODE, MENU_NM, MENU_LVL, CNNC_URL, MENU_DC, ACTVTY_AT, UPPER_MENU_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID ) VALUES ('MENU_0000000032','게시판 생성'                               ,2,'/cop/bbs/SelectBBSMasterInfs.do'                     ,'게시판 생성'                               ,1,'MENU_0000000002',SYSDATE,'SYSTEM');
INSERT INTO COMTNMOBILEMENUINFO ( MENU_CODE, MENU_NM, MENU_LVL, CNNC_URL, MENU_DC, ACTVTY_AT, UPPER_MENU_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID ) VALUES ('MENU_0000000033','게시판 사용정보'                           ,2,'/cop/com/selectBBSUseInfs.do'                        ,'게시판 사용정보'                           ,1,'MENU_0000000002',SYSDATE,'SYSTEM');
INSERT INTO COMTNMOBILEMENUINFO ( MENU_CODE, MENU_NM, MENU_LVL, CNNC_URL, MENU_DC, ACTVTY_AT, UPPER_MENU_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID ) VALUES ('MENU_0000000034','커뮤니티 관리'                             ,2,'/cop/cmy/selectCmmntyInfs.do'                        ,'커뮤니티 관리'                             ,1,'MENU_0000000002',SYSDATE,'SYSTEM');
                                                                                                                                                                                                                                                                                                                               
INSERT INTO COMTNMOBILEMENUINFO ( MENU_CODE, MENU_NM, MENU_LVL, CNNC_URL, MENU_DC, ACTVTY_AT, UPPER_MENU_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID ) VALUES ('MENU_0000000035','실시간 공지 서비스'                        ,2,'/mbl/com/rns/goRealtimeNoticeMsg.mdo'                ,'실시간 공지 서비스'                        ,1,'MENU_0000000002',SYSDATE,'SYSTEM');
INSERT INTO COMTNMOBILEMENUINFO ( MENU_CODE, MENU_NM, MENU_LVL, CNNC_URL, MENU_DC, ACTVTY_AT, UPPER_MENU_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID ) VALUES ('MENU_0000000036','모바일 기기 식별'                          ,2,'/mbl/com/mdi/goMobileDeviceIdent.mdo'                ,'모바일 기기 식별'                          ,1,'MENU_0000000002',SYSDATE,'SYSTEM');
INSERT INTO COMTNMOBILEMENUINFO ( MENU_CODE, MENU_NM, MENU_LVL, CNNC_URL, MENU_DC, ACTVTY_AT, UPPER_MENU_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID ) VALUES ('MENU_0000000037','동기화 서비스'                             ,2,'/mbl/com/syn/goMobileSyncList.mdo'                   ,'동기화 서비스'                             ,1,'MENU_0000000002',SYSDATE,'SYSTEM');
INSERT INTO COMTNMOBILEMENUINFO ( MENU_CODE, MENU_NM, MENU_LVL, CNNC_URL, MENU_DC, ACTVTY_AT, UPPER_MENU_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID ) VALUES ('MENU_0000000038','오프라인 웹 서비스'                        ,2,'/mbl/com/ows/goMobileOfflineWebList.mdo'             ,'오프라인 웹 서비스'                        ,1,'MENU_0000000002',SYSDATE,'SYSTEM');
INSERT INTO COMTNMOBILEMENUINFO ( MENU_CODE, MENU_NM, MENU_LVL, CNNC_URL, MENU_DC, ACTVTY_AT, UPPER_MENU_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID ) VALUES ('MENU_0000000039','위치정보연계 서비스 - 공공 지도'           ,2,'/mbl/com/geo/goGeoLocationPublicInqire.mdo'          ,'위치정보연계 서비스 - 공공 지도'           ,1,'MENU_0000000002',SYSDATE,'SYSTEM');
INSERT INTO COMTNMOBILEMENUINFO ( MENU_CODE, MENU_NM, MENU_LVL, CNNC_URL, MENU_DC, ACTVTY_AT, UPPER_MENU_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID ) VALUES ('MENU_0000000040','위치정보연계 서비스 - 민간 지도'           ,2,'/mbl/com/geo/goGeoLocationPrivateInqire.mdo'         ,'위치정보연계 서비스 - 민간 지도'           ,1,'MENU_0000000002',SYSDATE,'SYSTEM');
                                                                                                                                                                                                                                                                                                                               
INSERT INTO COMTNMOBILEMENUINFO ( MENU_CODE, MENU_NM, MENU_LVL, CNNC_URL, MENU_DC, ACTVTY_AT, UPPER_MENU_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID ) VALUES ('MENU_0000000041','실시간 공지 서비스(back)'                        ,2,'/mbl/com/rns/goRealtimeNoticeList.mdo'               ,'실시간 공지 서비스'                        ,1,'MENU_0000000002',SYSDATE,'SYSTEM');
INSERT INTO COMTNMOBILEMENUINFO ( MENU_CODE, MENU_NM, MENU_LVL, CNNC_URL, MENU_DC, ACTVTY_AT, UPPER_MENU_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID ) VALUES ('MENU_0000000042','모바일 기기 식별(back)'                          ,2,'/mbl/com/mdi/selectDeviceIdentList.mdo'              ,'모바일 기기 식별'                          ,1,'MENU_0000000002',SYSDATE,'SYSTEM');
INSERT INTO COMTNMOBILEMENUINFO ( MENU_CODE, MENU_NM, MENU_LVL, CNNC_URL, MENU_DC, ACTVTY_AT, UPPER_MENU_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID ) VALUES ('MENU_0000000043','동기화 서비스(back)'                             ,2,'/mbl/com/syn/selectSyncList.mdo'                     ,'동기화 서비스'                             ,1,'MENU_0000000002',SYSDATE,'SYSTEM');
INSERT INTO COMTNMOBILEMENUINFO ( MENU_CODE, MENU_NM, MENU_LVL, CNNC_URL, MENU_DC, ACTVTY_AT, UPPER_MENU_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID ) VALUES ('MENU_0000000044','오프라인 웹 서비스(back)'                        ,2,'/mbl/com/ows/selectOfflineWebList.mdo'               ,'오프라인 웹 서비스'                        ,1,'MENU_0000000002',SYSDATE,'SYSTEM');
INSERT INTO COMTNMOBILEMENUINFO ( MENU_CODE, MENU_NM, MENU_LVL, CNNC_URL, MENU_DC, ACTVTY_AT, UPPER_MENU_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID ) VALUES ('MENU_0000000045','위치정보연계(back)'                              ,2,'/mbl/com/geo/selectBuildingLocationInfoList.mdo'     ,'위치정보연계'                              ,1,'MENU_0000000002',SYSDATE,'SYSTEM');
                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                               
INSERT INTO COMTNMOBILEMENUINFO ( MENU_CODE, MENU_NM, MENU_LVL, CNNC_URL, MENU_DC, ACTVTY_AT, UPPER_MENU_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID ) VALUES ('MENU_0000000046','모바일 사진 앨범'                          ,2,'/mbl/com/mpa/goMobilePhotoList.mdo'                  ,'모바일 사진 앨범'                          ,0,'MENU_0000000003',SYSDATE,'SYSTEM');
INSERT INTO COMTNMOBILEMENUINFO ( MENU_CODE, MENU_NM, MENU_LVL, CNNC_URL, MENU_DC, ACTVTY_AT, UPPER_MENU_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID ) VALUES ('MENU_0000000047','모바일 차트/그래프'                        ,2,'/mbl/com/mcg/goMobileChartGraph.mdo'                 ,'모바일 차트/그래프'                        ,0,'MENU_0000000003',SYSDATE,'SYSTEM');
INSERT INTO COMTNMOBILEMENUINFO ( MENU_CODE, MENU_NM, MENU_LVL, CNNC_URL, MENU_DC, ACTVTY_AT, UPPER_MENU_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID ) VALUES ('MENU_0000000048','멀티미디어 제어'                           ,2,'/mbl/com/mlt/goMobileMultimediaList.mdo'             ,'멀티미디어 제어'                           ,0,'MENU_0000000003',SYSDATE,'SYSTEM');
INSERT INTO COMTNMOBILEMENUINFO ( MENU_CODE, MENU_NM, MENU_LVL, CNNC_URL, MENU_DC, ACTVTY_AT, UPPER_MENU_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID ) VALUES ('MENU_0000000049','OPEN-API 연계 서비스_대한민국정부포털 검색',2,'/mbl/com/oas/goKoreaGovPortalSearchResultList.mdo'   ,'OPEN-API 연계 서비스_대한민국정부포털 검색',0,'MENU_0000000003',SYSDATE,'SYSTEM');
INSERT INTO COMTNMOBILEMENUINFO ( MENU_CODE, MENU_NM, MENU_LVL, CNNC_URL, MENU_DC, ACTVTY_AT, UPPER_MENU_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID ) VALUES ('MENU_0000000050','MMS 서비스연계'                            ,2,'/mbl/com/mms/goMmsWrite.mdo'                         ,'MMS 서비스연계'                            ,0,'MENU_0000000003',SYSDATE,'SYSTEM');
                                                                                                                                                                                                                                                                                                                               
INSERT INTO COMTNMOBILEMENUINFO ( MENU_CODE, MENU_NM, MENU_LVL, CNNC_URL, MENU_DC, ACTVTY_AT, UPPER_MENU_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID ) VALUES ('MENU_0000000051','모바일 사진 앨범(back)'                          ,2,'/mbl/com/mpa/selectPhotoList.mdo'                    ,'모바일 사진 앨범'                          ,0,'MENU_0000000003',SYSDATE,'SYSTEM');
INSERT INTO COMTNMOBILEMENUINFO ( MENU_CODE, MENU_NM, MENU_LVL, CNNC_URL, MENU_DC, ACTVTY_AT, UPPER_MENU_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID ) VALUES ('MENU_0000000052','모바일 차트/그래프(back)'                        ,2,'/mbl/com/mcg/selectChartGraphList.mdo'               ,'모바일 차트/그래프'                        ,0,'MENU_0000000003',SYSDATE,'SYSTEM');
INSERT INTO COMTNMOBILEMENUINFO ( MENU_CODE, MENU_NM, MENU_LVL, CNNC_URL, MENU_DC, ACTVTY_AT, UPPER_MENU_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID ) VALUES ('MENU_0000000053','멀티미디어 제어(back)'                           ,2,'/mbl/com/mlt/selectMultimediaList.mdo'               ,'멀티미디어 제어'                           ,0,'MENU_0000000003',SYSDATE,'SYSTEM');
INSERT INTO COMTNMOBILEMENUINFO ( MENU_CODE, MENU_NM, MENU_LVL, CNNC_URL, MENU_DC, ACTVTY_AT, UPPER_MENU_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID ) VALUES ('MENU_0000000054','OPEN-API 연계 서비스(back)'                      ,2,'/mbl/com/oas/selectOpenApiInquiryHistoryList.mdo'    ,'OPEN-API 연계 서비스'                      ,0,'MENU_0000000003',SYSDATE,'SYSTEM');
INSERT INTO COMTNMOBILEMENUINFO ( MENU_CODE, MENU_NM, MENU_LVL, CNNC_URL, MENU_DC, ACTVTY_AT, UPPER_MENU_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID ) VALUES ('MENU_0000000055','MMS 서비스연계_MMS 전송 결과 조회(back)'         ,2,'/mbl/com/mms/selectMmsTransResultList.mdo'           ,'MMS 서비스연계_MMS 전송 결과 조회'         ,0,'MENU_0000000003',SYSDATE,'SYSTEM');
INSERT INTO COMTNMOBILEMENUINFO ( MENU_CODE, MENU_NM, MENU_LVL, CNNC_URL, MENU_DC, ACTVTY_AT, UPPER_MENU_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID ) VALUES ('MENU_0000000056','MMS 서비스연계_MMS 첨부파일 관리(back)'          ,2,'/mbl/com/mms/selectMmsAttachFileList.mdo'            ,'MMS 서비스연계_MMS 첨부파일 관리'          ,0,'MENU_0000000003',SYSDATE,'SYSTEM');
