
CREATE TABLE COMTNMOBILEMENUINFO
(
	MENU_CODE			VARCHAR(20) NOT NULL,
	MENU_NM      		VARCHAR(60) NULL,
	MENU_LVL			NUMERIC(5) NULL,
	CNNC_URL			VARCHAR(255) NULL,
	MENU_DC				VARCHAR(250) NULL,
	ACTVTY_AT			CHAR(1) NULL,
	UPPER_MENU_ID		VARCHAR(20) NULL,	
	FRST_REGIST_PNTTM	DATETIME NULL,	
	FRST_REGISTER_ID	VARCHAR(20) NULL,	
	LAST_UPDT_PNTTM		DATETIME NULL,	
	LAST_UPDUSR_ID		VARCHAR(20) NULL,
	 PRIMARY KEY (MENU_CODE)
)
;